### ISSUE TITLE
Addition of current temperature: display_temperature

### ISSUE THREAD

**Issue by Grtschnk** [Mmodarre/pyfujitsu#5]
Hi Mmodarre,

thank you for your work on this! Just installed it on my setup and enjoying it. I just added the current temperature into the source files. IIRC you mentioned you were not able to find this in the Fujitsu unit properties. It is called 'display_temperature' and is transmitted as 100 times the temperature in Fahrenheit. I am sorry I am not providing this as a pull request, I am not sure I'd get it all right.

**Comment by Grtschnk** [comment]
Okay, it looked like it worked, given the temperatures I had in the house at the moment. But in the end it doesnt seem right. Sorry about that.

**Comment by meichthys** [comment]
@Grtschnk  Why did you end up concluding that it didn't seem right?

Your initial finding seems right to me. My `display_temperature` value shows 7100 and my FGLair app shows 70 degrees F. I've also been able to confirm that the `display_temperature` has a direct relationship with the temp that the FGLair app reports (ie, when the FGLair app reports 74 degrees F, the `display_temperature` value shows 7300). It doesn't seem like a perfect relationship, but it seems close enough.

Also, i've noticed that for the `adjust_temperature` property, the temp doesn't always match exactly, and is transmitted as 10x the actual Celsius temp, so i don't think we can expect an exact match between `display_temperature` and what is displayed in the app.

**Comment by Grtschnk** [comment]
I think in the end it is the right temperature sensor. I mean, there has to be a temperature sensor in the unit somewhere. And it matches the temperature the FGLair app shows.

But for me, this temperature measurement does not seem very useful. It does not match the temperature I am measuring and feeling inside the room. (Out by several degrees)
Likely that the temperature up at the ceiling (somewhere inside/on the unit) behaves differently.

**Comment by meichthys** [comment]
@Grtschnk I think you're right. I've noticed that my heatpump temperature on the in-home remote control is always a few degrees off from my other oil burner thermostats in the same room.

**Comment by michaelmaston** [comment]
This property doesn't show up in the 80+ properties I can pull from the Fujitsu cloud.  Perhaps it isn't supported on all Fujitsu units for some reason?  Accuracy aside, it seems like knowing the current room temp is a pretty useful piece of info and yet my properties (and FGLair app) don't show this value at all for any of the 4 Fujitsu minisplit units I own.
